import { ReportLevelEnum, type MonitorConfig, type ErrorInfo, type MonitorPlugin } from './type';
export declare class FrontendMonitor {
    private config;
    private storageQueue;
    private removedItems;
    private fingerprint;
    private oldFingerprint;
    getTimestamp(): number;
    formatTimestamp(format?: string, timestamp?: number): string;
    init(config: Partial<MonitorConfig>): void;
    getFingerprint(): string;
    setFingerprint(fingerprint: string): void;
    private log;
    error(pluginName: string, message: string, extraData?: Record<string, any>): void;
    warn(pluginName: string, message: string, extraData?: Record<string, any>): void;
    info(pluginName: string, message: string, extraData?: Record<string, any>): void;
    debug(pluginName: string, message: string, extraData?: Record<string, any>): void;
    private checkAndReportStored;
    updateReportLevel(level: keyof typeof ReportLevelEnum): void;
    getStorageQueue(): ErrorInfo[];
    clearStorageQueue(): void;
    reportStorageQueue(): void;
    reportRemovedItems(): void;
    reportRestInfo(): void;
    private report;
    destroy(): void;
}
declare const monitor: FrontendMonitor;
export { ReportLevelEnum, monitor };
export type { MonitorConfig, ErrorInfo, MonitorPlugin };
