export default function initTable(db) {
  db.exec(`
  CREATE TABLE IF NOT EXISTS error_info (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    platform TEXT,
    plugin_name TEXT,
    message TEXT,
    page TEXT,
    timestamp INTEGER,
    date TEXT,
    level TEXT,
    device_width INTEGER,
    device_height INTEGER,
    device_pixel_ratio REAL,
    fingerprint TEXT,
    old_fingerprint TEXT,
    ip TEXT,
    error_info TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )
`);
  db.exec(`
  CREATE TABLE IF NOT EXISTS request_info (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    platform TEXT,
    plugin_name TEXT,
    message TEXT,
    page TEXT,
    timestamp INTEGER,
    date TEXT,
    level TEXT,
    device_width INTEGER,
    device_height INTEGER,
    device_pixel_ratio REAL,
    fingerprint TEXT,
    old_fingerprint TEXT,
    ip TEXT,
    url TEXT,
    method TEXT,
    start_time INTEGER,
    end_time INTEGER,
    duration INTEGER,
    error_info TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )
`);
  db.exec(`
  CREATE TABLE IF NOT EXISTS page_lifecycle (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    platform TEXT,
    plugin_name TEXT,
    message TEXT,
    page TEXT,
    timestamp INTEGER,
    date TEXT,
    level TEXT,
    device_width INTEGER,
    device_height INTEGER,
    device_pixel_ratio REAL,
    fingerprint TEXT,
    old_fingerprint TEXT,
    ip TEXT,
    change_type TEXT,
    enter_time INTEGER,
    leave_time INTEGER,
    current_route TEXT,
    previous_route TEXT,
    route TEXT,
    target TEXT,
    duration INTEGER,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )
`);
  db.exec(`
  CREATE TABLE IF NOT EXISTS resource_info (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    platform TEXT,
    plugin_name TEXT,
    message TEXT,
    page TEXT,
    timestamp INTEGER,
    date TEXT,
    level TEXT,
    device_width INTEGER,
    device_height INTEGER,
    device_pixel_ratio REAL,
    fingerprint TEXT,
    old_fingerprint TEXT,
    ip TEXT,
    name TEXT,
    entry_type TEXT,
    start_time INTEGER,
    duration INTEGER,
    initiator_type TEXT,
    next_hop_protocol TEXT,
    worker_start INTEGER,
    redirect_start INTEGER,
    redirect_end INTEGER,
    fetch_start INTEGER,
    domain_lookup_start INTEGER,
    domain_lookup_end INTEGER,
    connect_start INTEGER,
    connect_end INTEGER,
    secure_connection_start INTEGER,
    request_start INTEGER,
    response_start INTEGER,
    response_end INTEGER,
    transfer_size INTEGER,
    encoded_body_size INTEGER,
    decoded_body_size INTEGER,
    server_timing TEXT,
    cached TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )
`);
  db.exec(`
  CREATE TABLE IF NOT EXISTS user_behavior (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    platform TEXT,
    plugin_name TEXT,
    message TEXT,
    page TEXT,
    timestamp INTEGER,
    date TEXT,
    level TEXT,
    device_width INTEGER,
    device_height INTEGER,
    device_pixel_ratio REAL,
    fingerprint TEXT,
    old_fingerprint TEXT,
    ip TEXT,
    x INTEGER,
    y INTEGER,
    scrollX INTEGER,
    scrollY INTEGER,
    local_name TEXT,
    class_name TEXT,
    class_list TEXT,
    dom_id TEXT,
    node_name TEXT,
    tag_name TEXT,
    data_set TEXT,
    path TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )
`);
}